### PR TITLE
Update dependencies and use multi targeting

### LINKED ISSUE #14: Update dependencies
We should update our dependencies to use `Grpc 2.x` and use the latest patch releases of the minimal required versions.

As this is a library project, we should keep using the oldest possible versions.

To decrease the need for support dependencies, we should use multi targeting for `net45;netstandard1.5;netstandard2.0` instead of only `netstandard1.5`.

### PR DESCRIPTION
**Pull request by Falco20019**
Fixes #14 
Superseeds #13

This upgrades the dependencies to the latest possible minimal version and adds multi targets for `netstandard2.0` and `net45`.

### CODE REVIEW

**Comment by Falco20019** [comment]
Waiting for https://github.com/grpc/grpc/issues/20782 to be resolved before merging.

**Comment by pcwiese** [comment]
That fix you referenced appears to be resolved. Can you you merge this in now?

**Comment by Falco20019** [comment]
I will check it next week to make sure nothing breaks. Don’t have time this weekend, sorry.

**Comment by Falco20019** [comment]
@pcwiese Thanks for your patience. I just released 0.2.0 including those changes. If you still have issues, please let me know.

**Comment by pcwiese** [comment]
Fantastic. Thanks so much!

**Pull request merged**
